Import of SIMES/LJ-Simple-0.14 from CPAN.
gitpan-cpan-distribution: LJ-Simple
gitpan-cpan-version:      0.14
gitpan-cpan-path:         SIMES/LJ-Simple-0.14.tar.gz
gitpan-cpan-author:       SIMES
gitpan-cpan-maturity:     released

diff --git a/Makefile.PL b/Makefile.PL
--- a/Makefile.PL
+++ b/Makefile.PL
@@ -63,6 +63,22 @@ pkg: rebuild-pkg version manifypods pure_all
 	build-pkg -n %PKG%-v%VERSION%.pkg -K
 	mv InstallPackage/*.pkg .
 
+##
+## Used for tagging the CVS tree with the current version
+##
+tag:
+	\@currtag=`cvs status -v Makefile.PL | grep '(revision: ' | head -1 | awk '{print \$\$1}'` ; \\
+	symtag="v\$(VERSION_SYM)" ; \\
+	if [ "\$\${currtag}" = "\$\${symtag}" ]; then \\
+	  echo "Tag already at \$\${symtag}"; \\
+	  exit 0; \\
+	fi ; \\
+	/usr/bin/echo "\\nWill tag to \$\${symtag}; are you sure? [Y/N] \\c" ; \\
+	read yesno ; \\
+	if [ "\$\${yesno}" != "Y" ]; then echo "Aborting" ; exit 255 ; fi ; \\
+	cvs update ; \\
+	cvs tag \$\${symtag}
+
 EOF
 }
 
